// machine generated by incbin, probably not a good idea to hand edit.

#ifndef MEDIA_BLOB_H_
#define MEDIA_BLOB_H_
extern char snd__tromboon_sample_ogg[382186];
extern char img__doodle_png[14271];
extern char fnt__inconsolata_otf[58465];
extern char txt__hello_txt[35];
extern char txt__hello_txt_gz[45];

#endif  // MEDIA_BLOB_H_
