#!/bin/bash

echo
echo Zapping
./zap

echo
echo Tweezer inserting license
tweezer -r ./src -l ./license -i
tweezer -r ./test -l ./license -i

echo
echo Git Commit
git add .
git commit --amend -C HEAD

echo
echo Git Pushing
git push

echo
echo Tweezering extracting licenses
tweezer -r ./src -l ./license -x
tweezer -r ./test -l ./license -x

echo
echo Git update commit
git add .
git commit --amend -C HEAD
